# Generated by Django 4.1 on 2022-08-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'servicioapp', 'verbose_name_plural': 'serviciosapp'},
        ),
    ]
