# Generated by Django 4.1 on 2022-11-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('comentarios', models.CharField(blank=True, max_length=300, null=True)),
                ('paciente', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
