# Generated by Django 4.1 on 2022-11-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.CharField(max_length=300),
        ),
    ]
